# Copyright The Linux Foundation and each contributor to LFX.
---
site_name: 'LFX One Mailing List Service'
site_description: 'Documentation for LFX One Mailing List Service'
nav:
  - Home: index.md
plugins:
  - techdocs-core
