# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
apiVersion: v2
name: lfx-v2-mailing-list-service
description: LFX Platform V2 Mailing List Service chart
type: application
version: 0.1.5
appVersion: "latest"
